local H, T = ...

local function ids(list)
    local out = {}
    for _, o in ipairs(list) do out[#out + 1] = o.user_id end
    table.sort(out)
    return out
end

local function row(uid)
    return H.query("SELECT * FROM evora_police_officers WHERE user_id = ?", { uid })[1]
end

T.describe("الشؤون — scope-enforced administration", function()
    H.boot({ configure = function(cfg) cfg.Webhooks.statistics = "https://discord.test/stats" end })
    local cmd = H.connect(40, { name = "Commander", groups = { "ps_commander" } })
    local psOfficer = H.connect(41, { name = "PsOfficer", groups = { "ps_officer" } })
    local trOfficer = H.connect(42, { name = "TrOfficer", groups = { "traffic_officer" } })
    local minister = H.connect(43, { name = "Minister", groups = { "interior_minister" } })
    local pm = H.connect(44, { name = "PrimeMinister", groups = { "prime_minister" } })
    local citizen = H.connect(45, { name = "Hossam" })
    local soldier = H.connect(46, { name = "Soldier", groups = { "sector_officer" } })

    T.it("shows the commander only the tiles and sectors in scope", function()
        local ok, o = H.rpc(cmd, "affairs:overview", {})
        T.truthy(ok, tostring(o))
        T.has(o.tiles, "recruit")
        T.has(o.tiles, "recall")
        T.has(o.tiles, "statistics")
        T.eq(table.concat(o.scope, ","), "الأمن العام")
        T.eq(o.stats.officers, 2, "commander + officer of Public Security")
    end)

    T.it("lists only officers inside the scope of the permission", function()
        local _, list = H.rpc(cmd, "affairs:officers", { perm = "dismiss" })
        T.eq(table.concat(ids(list), ","), "41")
        H.advance(1000)
        local _, mlist = H.rpc(minister, "affairs:officers", { perm = "dismiss" })
        T.eq(table.concat(ids(mlist), ","), "40,41,42")
        H.advance(1000)
        local _, plist = H.rpc(pm, "affairs:officers", { perm = "dismiss" })
        T.eq(table.concat(ids(plist), ","), "40,41,42,43,46")
    end)

    T.it("recruits a citizen only into ranks of the administrator's scope", function()
        local ok, err = H.rpc(cmd, "affairs:recruit", { user_id = 45, rank = "traffic_officer" })
        T.falsy(ok)
        T.eq(err, L("err_out_of_scope"))
        H.advance(2000)
        ok, err = H.rpc(cmd, "affairs:recruit", { user_id = 45, rank = "ps_commander" })
        T.falsy(ok, "cannot appoint an equal rank")
        H.advance(2000)
        ok, err = H.rpc(cmd, "affairs:recruit", { user_id = 45, rank = "ps_patrol" })
        T.truthy(ok, tostring(err))
        T.eq(table.concat(H.groups(45), ","), "ps_patrol")
        T.eq(row(45).rank_group, "ps_patrol")
        T.eq(row(45).active, 1)
    end)

    T.it("promotes by replacing the ranks the administrator manages", function()
        H.advance(2000)
        local ok, err = H.rpc(cmd, "affairs:recruit", { user_id = 45, rank = "ps_officer" })
        T.truthy(ok, tostring(err))
        T.eq(table.concat(H.groups(45), ","), "ps_officer")
    end)

    T.it("refuses to dismiss officers of another sector", function()
        H.advance(2000)
        local ok, err = H.rpc(cmd, "affairs:dismiss", { user_id = 42 })
        T.falsy(ok)
        T.eq(err, L("err_out_of_scope"))
        H.advance(2000)
        ok, err = H.rpc(cmd, "affairs:dismiss", { user_id = 43 })
        T.falsy(ok, "cannot dismiss the minister")
    end)

    T.it("requires the administrator's own F5 to dismiss and rejects spoofed answers", function()
        H.advance(2000)
        local id = H.rpcStart(cmd, "affairs:dismiss", { user_id = 45 })
        T.falsy((H.rpcResult(cmd, id)), "waiting for confirmation")
        local confirmId = H.pendingConfirm(cmd)
        T.truthy(confirmId)
        local ok, err = H.rpc(psOfficer, "confirm:answer", { id = confirmId, accepted = true })
        T.falsy(ok, "another player cannot answer")
        T.eq(err, L("err_invalid_request"))
        T.eq(table.concat(H.groups(45), ","), "ps_officer", "nothing happened yet")
        H.confirm(cmd, false)
        local done, ok2, err2 = H.rpcResult(cmd, id)
        T.truthy(done)
        T.falsy(ok2, "F6 cancels")
        T.eq(err2, L("confirm_self_rejected"))
        T.eq(table.concat(H.groups(45), ","), "ps_officer")
    end)

    T.it("dismisses after F5 and deactivates the record", function()
        H.advance(2000)
        local id = H.rpcStart(cmd, "affairs:dismiss", { user_id = 45 })
        H.confirm(cmd, true)
        local done, ok, err = H.rpcResult(cmd, id)
        T.truthy(done and ok, tostring(err))
        T.eq(#H.groups(45), 0)
        T.eq(row(45).active, 0)
    end)

    T.it("queues the dismissal of an offline officer until they join", function()
        H.disconnect(trOfficer)
        H.advance(2000)
        local id = H.rpcStart(minister, "affairs:dismiss", { user_id = 42 })
        H.confirm(minister, true)
        local done, ok, err = H.rpcResult(minister, id)
        T.truthy(done and ok, tostring(err))
        T.eq(#H.query("SELECT * FROM evora_police_pending WHERE user_id = 42"), 1)
        T.eq(row(42).active, 0)
        T.eq(H.groups(42)[1], "traffic_officer", "vRP groups untouched while offline")
        trOfficer = H.connect(42, { name = "TrOfficer" })
        T.eq(#H.groups(42), 0, "applied on join")
        T.eq(#H.query("SELECT * FROM evora_police_pending WHERE user_id = 42"), 0)
    end)

    T.it("resets attendance / fines / data inside the scope only", function()
        H.query("UPDATE evora_police_officers SET attendance_total = 5000, fines_issued = 9, jails_issued = 4, vacation_balance = 3 WHERE user_id = 41")
        H.advance(2000)
        local id = H.rpcStart(cmd, "affairs:reset", { user_id = 41, kind = "attendance" })
        H.confirm(cmd, true)
        local _, ok, err = H.rpcResult(cmd, id)
        T.truthy(ok, tostring(err))
        T.eq(row(41).attendance_total, 0)
        T.eq(row(41).fines_issued, 9)
        H.advance(2000)
        id = H.rpcStart(cmd, "affairs:reset", { user_id = 41, kind = "data" })
        H.confirm(cmd, true)
        _, ok = H.rpcResult(cmd, id)
        T.truthy(ok)
        local r = row(41)
        T.eq(r.fines_issued, 0)
        T.eq(r.jails_issued, 0)
        T.eq(r.vacation_balance, 3, "vacationBalance is not part of the default data reset")
        H.advance(2000)
        local ok2, err2 = H.rpc(cmd, "affairs:reset", { user_id = 42, kind = "fines" })
        T.falsy(ok2)
    end)

    T.it("adds vacation balance with the configured cap", function()
        H.advance(2000)
        local ok, res = H.rpc(cmd, "affairs:vacationBalance", { user_id = 41, days = 5 })
        T.truthy(ok, tostring(res))
        T.eq(res.balance, 8)
        H.advance(2000)
        ok, res = H.rpc(cmd, "affairs:vacationBalance", { user_id = 41, days = 60 })
        T.eq(res.balance, Config.Vacation.MaxBalance)
    end)

    T.it("returns officer details with the actions allowed on them", function()
        local ok, d = H.rpc(cmd, "affairs:officer", { user_id = 41 })
        T.truthy(ok, tostring(d))
        T.eq(d.name, "PsOfficer")
        T.eq(d.rank, "ضابط أمن عام")
        T.truthy(d.actions.dismiss and d.actions.resetData and d.actions.monitor)
        T.falsy(d.actions.vacationBreak)
        local ok2 = H.rpc(cmd, "affairs:officer", { user_id = 46 })
        T.falsy(ok2, "defense soldier is out of scope")
    end)

    T.it("broadcasts to military personnel or to every citizen", function()
        H.clearEvents()
        local ok, res = H.rpc(cmd, "affairs:broadcast", { audience = "officers", message = "اجتماع عاجل" })
        T.truthy(ok, tostring(res))
        local got = H.uiEvents(psOfficer, "broadcast")
        T.eq(#got, 1)
        T.eq(got[1].title, Config.Broadcast.OfficerTitle)
        T.eq(got[1].message, "اجتماع عاجل")
        T.eq(#H.uiEvents(citizen, "broadcast"), 0, "citizens do not receive officer broadcasts")
        local ok2, err2 = H.rpc(cmd, "affairs:broadcast", { audience = "citizens", message = "تنبيه" })
        T.falsy(ok2, "cooldown")
        T.eq(err2, L("err_cooldown"))
        H.advance((Config.Broadcast.Cooldown + 1) * 1000)
        T.truthy((H.rpc(cmd, "affairs:broadcast", { audience = "citizens", message = "تنبيه" })))
        T.eq(#H.uiEvents(citizen, "broadcast"), 1)
    end)

    T.it("recalls officers of the scope with F5/F6 and reports the results", function()
        local ps2 = H.connect(47, { name = "PsPatrol", groups = { "ps_patrol" } })
        H.clearEvents()
        local ok, snap = H.rpc(cmd, "affairs:recall", { message = "تجمع في المركز" })
        T.truthy(ok, tostring(snap))
        T.eq(snap.counts.pending, 2)
        T.truthy(H.pendingConfirm(psOfficer))
        T.falsy(H.pendingConfirm(soldier), "defense is out of scope")
        T.falsy(H.pendingConfirm(trOfficer), "traffic is out of scope")
        H.confirm(psOfficer, true)
        T.truthy(H.lastClientEvent(psOfficer, "evora_police:waypoint"), "waypoint to the caller")
        T.truthy(Evora.Officers.isOnDuty(41), "auto clock-in")
        H.advance((Config.Recall.Timeout + 2) * 1000)
        local push = H.lastClientEvent(cmd, "evora_police:ipad:push")
        T.eq(push.args[1], "recall")
        T.eq(push.args[2].counts.accepted, 1)
        T.eq(push.args[2].counts.timeout, 1)
        T.truthy(push.args[2].done)
        H.disconnect(ps2)
    end)

    T.it("starts real spectate only on officers inside the scope", function()
        H.clearEvents()
        local ok, err = H.rpc(cmd, "affairs:monitor", { user_id = 41 })
        T.truthy(ok, tostring(err))
        local ev = H.lastClientEvent(cmd, "evora_police:spectate:start")
        T.eq(ev.args[1].id, 41)
        T.eq(ev.args[1].name, "PsOfficer")
        T.truthy(Evora.Spectate.isSpectating(cmd))
        T.truthy((H.rpc(cmd, "spectate:stop", {})))
        T.falsy(Evora.Spectate.isSpectating(cmd))
        local ok2 = H.rpc(cmd, "affairs:monitor", { user_id = 46 })
        T.falsy(ok2)
    end)

    T.it("ends the spectate when the target leaves", function()
        H.rpc(cmd, "affairs:monitor", { user_id = 41 })
        H.disconnect(psOfficer)
        T.falsy(Evora.Spectate.isSpectating(cmd))
        local ev = H.lastClientEvent(cmd, "evora_police:spectate:stop")
        T.eq(ev.args[1], "target_left")
        psOfficer = H.connect(41, { name = "PsOfficer" })
    end)

    T.it("ranks ONE combined Top 10 inside the scope and sends it to Discord", function()
        H.query("UPDATE evora_police_officers SET attendance_total = 36000, fines_issued = 2 WHERE user_id = 41")
        H.query("UPDATE evora_police_officers SET attendance_total = 3600, fines_issued = 40 WHERE user_id = 40")
        H.query("UPDATE evora_police_officers SET attendance_total = 999999, fines_issued = 999, active = 1 WHERE user_id = 46")
        local ok, top = H.rpc(cmd, "affairs:top", {})
        T.truthy(ok, tostring(top))
        T.eq(#top, 3, "Public Security officers (40, 41, 47) only")
        for _, o in ipairs(top) do T.falsy(o.user_id == 46, "defense soldier must not appear") end
        T.eq(top[1].user_id, 40, "3600s*1 + 40*0.5 = 21 > 10 + 1")
        T.eq(top[1].position, 1)
        T.eq(top[2].user_id, 41)
        local before = #H.http
        T.truthy((H.rpc(cmd, "affairs:topWebhook", {})))
        H.advance(2000)
        T.eq(#H.http, before + 1)
        local payload = json.decode(H.http[#H.http].body)
        T.eq(H.http[#H.http].url, "https://discord.test/stats")
        T.contains(payload.embeds[1].fields[1].name, "Commander | ID: 40")
        T.contains(payload.embeds[1].fields[1].value, "الأمن العام")
        local ok2, err2 = H.rpc(cmd, "affairs:topWebhook", {})
        T.falsy(ok2, "webhook cooldown")
    end)
end)
