local H, T = ...

local function officerRow(uid)
    return H.query("SELECT * FROM evora_police_officers WHERE user_id = ?", { uid })[1]
end

T.describe("Duty, attendance and military code", function()
    H.boot({ configure = function(cfg) cfg.Integrations.Radio.type = "statebag" end })
    local officer = H.connect(10, { name = "Rayy", groups = { "ps_officer" } })

    T.it("creates the officer record on join with the default vacation balance", function()
        local row = officerRow(10)
        T.truthy(row, "record")
        T.eq(row.rank_group, "ps_officer")
        T.eq(row.sector, "Interior.PublicSecurity")
        T.eq(row.ministry, "Interior")
        T.eq(row.vacation_balance, Config.Vacation.DefaultBalance)
        T.eq(row.name, "Rayy")
    end)

    T.it("counts attendance only while clocked in", function()
        H.advance(10 * 60 * 1000) -- 10 min off duty
        T.truthy((H.rpc(officer, "office:clock", {})))
        T.truthy(Evora.Officers.isOnDuty(10))
        H.advance(30 * 60 * 1000)
        local ok, res = H.rpc(officer, "office:clock", {})
        T.truthy(ok)
        T.falsy(res.onDuty)
        local row = officerRow(10)
        T.near(row.attendance_total, 1800, 2)
        T.eq(row.on_duty, 0)
        local sessions = H.query("SELECT * FROM evora_police_attendance WHERE user_id = 10")
        T.eq(#sessions, 1)
        T.near(sessions[1].duration, 1800, 2)
    end)

    T.it("shows the live session in مكتبي", function()
        H.advance(3000)
        T.truthy((H.rpc(officer, "office:clock", {})))
        H.advance(120 * 1000)
        local ok, office = H.rpc(officer, "ipad:office", {})
        T.truthy(ok)
        T.truthy(office.onDuty)
        T.near(office.session, 120, 2)
        T.near(office.attendance, 1920, 3)
    end)

    T.it("clocks out on disconnect and keeps the time", function()
        H.advance(60 * 1000)
        H.disconnect(officer)
        local row = officerRow(10)
        T.eq(row.on_duty, 0)
        T.near(row.attendance_total, 1980, 3) -- 1800 + 120 + 60
    end)

    T.it("resumes a session after a resource restart", function()
        officer = H.connect(10, { name = "Rayy" })
        H.advance(3000)
        T.truthy((H.rpc(officer, "office:clock", {})))
        H.advance(10 * 60 * 1000)
        H.restart()
        T.truthy(Evora.Officers.isOnDuty(10), "session resumed after restart")
        H.advance(5 * 60 * 1000)
        T.truthy((H.rpc(officer, "office:clock", {})))
        T.near(officerRow(10).attendance_total, 1980 + 900, 4)
    end)

    T.it("closes a crashed session from the last heartbeat only", function()
        H.disconnect(officer)
        local now = os.time()
        H.query("UPDATE evora_police_officers SET on_duty = 1, duty_started_at = ?, duty_last_seen = ? WHERE user_id = 10",
            { now - 3600, now - 1200 })
        local before = officerRow(10).attendance_total
        H.restart()
        local row = officerRow(10)
        T.eq(row.on_duty, 0)
        T.near(row.attendance_total - before, 2400, 2)
    end)

    T.it("toggles duty from the Builder Menu with the right label", function()
        officer = H.connect(10, { name = "Rayy" })
        local main = H.mainMenu(officer)
        H.choose(officer, main, "الشرطة")
        T.has(H.labels(H.menu(officer)), "تسجيل الدخول")
        H.select(officer, "تسجيل الدخول")
        T.truthy(Evora.Officers.isOnDuty(10))
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        T.has(H.labels(H.menu(officer)), "تسجيل الخروج")
    end)

    T.it("stores a sanitised military code and pushes it to the radio adapter", function()
        H.advance(3000)
        local ok, res = H.rpc(officer, "office:setCode", { code = "<b>A-12</b>" })
        T.truthy(ok)
        T.eq(res.code, "bA-12/b")
        T.eq(officerRow(10).military_code, "bA-12/b")
        T.eq(H.statebags[officer].callsign, "bA-12/b")
    end)

    T.it("lists only clocked-in sector officers in المتصلين", function()
        local minister = H.connect(11, { name = "Minister", groups = { "interior_minister" } })
        local offDuty = H.connect(12, { name = "OffDuty", groups = { "traffic_officer" } })
        H.advance(3000)
        T.truthy((H.rpc(minister, "office:clock", {})))
        local ok, res = H.rpc(officer, "ipad:online", {})
        T.truthy(ok)
        T.eq(#res.list, 1, "only the sector officer on duty")
        T.eq(res.list[1].user_id, 10)
        T.eq(res.list[1].name, "Rayy")
        T.eq(res.list[1].code, "bA-12/b")
        T.eq(res.list[1].sectorLabel, "الأمن العام")
        H.disconnect(minister)
        H.disconnect(offDuty)
    end)

    T.it("clocks out and deactivates an officer whose rank is removed elsewhere", function()
        Evora.Framework.removeUserGroup(10, "ps_officer")
        H.advance(1000)
        T.falsy(Evora.Officers.isOnDuty(10))
        T.eq(officerRow(10).active, 0)
    end)
end)
