local H, T = ...

local function openFine(officer, category, fineLabel)
    H.choose(officer, H.mainMenu(officer), "الشرطة")
    H.select(officer, "المخالفات")
    H.select(officer, category)
    H.selectMatching(officer, fineLabel)
end

T.describe("Fines", function()
    local chat = {}
    H.boot()
    local officer = H.connect(70, { name = "Rayy", groups = { "ps_officer" }, coords = { x = 0, y = 0, z = 30 } })
    local target = H.connect(71, { name = "Hossam", coords = { x = 2, y = 0, z = 30 }, wallet = 500, bank = 5000 })
    local far = H.connect(72, { name = "Far", coords = { x = 300, y = 0, z = 30 } })

    T.it("requires the officer to be on duty", function()
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "المخالفات")
        T.eq(H.lastNotification(officer), L("err_not_on_duty"))
        T.truthy((H.rpc(officer, "office:clock", {})))
    end)

    T.it("lists only nearby players in the target picker", function()
        openFine(officer, "مخالفات مرورية", "تجاوز السرعة")
        local labels = H.labels(H.menu(officer))
        T.has(labels, "Hossam | ID: 71")
        T.hasNot(labels, "Far | ID: 72")
    end)

    T.it("records nothing when the target presses F6", function()
        H.select(officer, "Hossam | ID: 71")
        local id, card = H.pendingConfirm(target)
        T.truthy(id, "confirmation shown to the target")
        T.contains(card.message, "Rayy | ID: 70")
        T.eq(card.accept, "F5")
        H.confirm(target, false)
        T.eq(#H.query("SELECT id FROM evora_police_fines"), 0)
        T.eq(H.lastNotification(officer), L("confirm_rejected"))
    end)

    T.it("ignores an acceptance sent by the officer instead of the target", function()
        H.advance(6000)
        openFine(officer, "مخالفات مرورية", "تجاوز السرعة")
        H.select(officer, "Hossam | ID: 71")
        local id = H.pendingConfirm(target)
        local ok = H.rpc(officer, "confirm:answer", { id = id, accepted = true })
        T.falsy(ok)
        T.eq(#H.query("SELECT id FROM evora_police_fines"), 0)
        H.confirm(target, true)
    end)

    T.it("records the fine after F5, counts it and announces it in chat", function()
        local f = H.query("SELECT * FROM evora_police_fines")[1]
        T.truthy(f, "fine row")
        T.eq(f.target_name, "Hossam")
        T.eq(f.officer_name, "Rayy")
        T.eq(f.amount, 1500)
        T.eq(f.status, "unpaid")
        T.eq(H.query("SELECT fines_issued FROM evora_police_officers WHERE user_id = 70")[1].fines_issued, 1)
        local msg
        for _, e in ipairs(H.sent) do
            if e.name == "chat:addMessage" then msg = e.args[1].args[2] end
        end
        T.eq(msg, "العسكري Rayy | ID: 70 قام بمخالفة اللاعب Hossam | ID: 71 بقيمة 1,500$")
    end)

    T.it("refuses a target that walked away before the pick", function()
        H.advance(6000)
        openFine(officer, "مخالفات عامة", "إزعاج عام")
        H.move(target, 50, 0, 30)
        H.select(officer, "Hossam | ID: 71")
        T.eq(H.lastNotification(officer), L("target_too_far"))
        T.falsy(H.pendingConfirm(target))
        H.move(target, 2, 0, 30)
    end)

    T.it("answers the fine inquiry with every fine and its status", function()
        H.clearEvents()
        H.prompts(officer, { "71" })
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "استعلامات")
        H.select(officer, "استعلام عن مخالفات")
        local panel = H.uiEvents(officer, "panel")[1]
        T.eq(panel.kind, "fines")
        T.eq(#panel.data.list, 1)
        T.eq(panel.data.list[1].status, "unpaid")
        T.eq(panel.data.list[1].officer.name, "Rayy")
        T.eq(panel.data.unpaidTotal, 1500)
    end)

    T.it("only lets citizens pay at a payment point", function()
        local ok, err = H.rpc(target, "fines:open", {})
        T.falsy(ok)
        T.eq(err, L("fine_point_far"))
        local p = Config.Fines.PaymentPoints[1].coords
        H.move(target, p.x, p.y, p.z)
        H.advance(1500)
        local ok2, data = H.rpc(target, "fines:open", {})
        T.truthy(ok2, tostring(data))
        T.eq(data.count, 1)
        T.eq(data.total, 1500)
    end)

    T.it("charges wallet then bank and marks fines paid once", function()
        local ok, res = H.rpc(target, "fines:pay", { all = true })
        T.truthy(ok, tostring(res))
        T.eq(res.count, 0)
        T.eq(H.user(71).wallet, 0)
        T.eq(H.user(71).bank, 4000)
        T.eq(H.query("SELECT status FROM evora_police_fines")[1].status, "paid")
        H.advance(2000)
        local ok2, err2 = H.rpc(target, "fines:pay", { all = true })
        T.falsy(ok2)
        T.eq(err2, L("fine_none_selected"))
    end)

    T.it("refuses the payment without enough money", function()
        H.query("INSERT INTO evora_police_fines (target_id, target_name, officer_id, officer_name, category, category_label, fine_id, label, amount, status, created_at) VALUES (71, 'Hossam', 70, 'Rayy', 'criminal', 'جنائية', 'weapon', 'سلاح', 90000, 'unpaid', 1)")
        H.advance(2000)
        local ok, err = H.rpc(target, "fines:pay", { all = true })
        T.falsy(ok)
        T.contains(err, "90,000")
        T.eq(H.user(71).bank, 4000)
    end)
end)
