local H, T = ...

local function impound(officer, plate, reasonPattern)
    H.prompts(officer, { plate })
    H.choose(officer, H.mainMenu(officer), "الشرطة")
    H.select(officer, "حجز المركبات")
    H.select(officer, "حجز مركبة")
    if reasonPattern then H.selectMatching(officer, reasonPattern) end
end

T.describe("Vehicle impound", function()
    H.boot({ configure = function(cfg) cfg.Webhooks.impound = "https://discord.test/impound" end })
    local officer = H.connect(100, { name = "Rayy", groups = { "ps_officer" }, coords = { x = 0, y = 0, z = 30 } })
    local commander = H.connect(101, { name = "Commander", groups = { "ps_commander" }, coords = { x = 0, y = 3, z = 30 } })
    local owner = H.connect(102, { name = "Hossam", coords = { x = 500, y = 500, z = 30 }, wallet = 10000 })
    H.query("INSERT INTO vrp_user_identities (user_id, registration) VALUES (102, '555AAA')")
    H.query("INSERT INTO vrp_user_vehicles (user_id, vehicle) VALUES (102, 'sultan')")
    local car = H.addVehicle("P 555AAA", { x = 3, y = 0, z = 30 }, "sultan")
    H.addVehicle("P 777BBB", { x = 400, y = 0, z = 30 }, "adder")
    H.rpc(officer, "office:clock", {})
    H.rpc(commander, "office:clock", {})

    T.it("requires the officer to stand next to the typed plate", function()
        impound(officer, "P 777BBB")
        T.eq(H.lastNotification(officer), L("impound_vehicle_far"))
    end)

    T.it("refuses plates that no garage owner is registered for", function()
        H.addVehicle("P 999ZZZ", { x = 2, y = 2, z = 30 }, "adder")
        impound(officer, "p 999zzz")
        T.contains(H.lastNotification(officer), "999ZZZ")
        T.eq(#H.query("SELECT id FROM evora_police_impounds"), 0)
    end)

    T.it("impounds after the officer's F5 with owner, reason, fee and location", function()
        impound(officer, "P 555AAA", "وقوف مخالف")
        local id, card = H.pendingConfirm(officer)
        T.truthy(id, "officer confirms")
        local text = ""
        for _, row in ipairs(card.details) do text = text .. row[1] .. "=" .. row[2] .. ";" end
        T.contains(text, "Hossam | ID: 102")
        T.contains(text, "sultan")
        T.contains(text, "1,500")
        H.confirm(officer, true)
        local rec = H.query("SELECT * FROM evora_police_impounds")[1]
        T.truthy(rec, "record")
        T.eq(rec.plate, "P 555AAA")
        T.eq(rec.owner_id, 102)
        T.eq(rec.owner_name, "Hossam")
        T.eq(rec.officer_name, "Rayy")
        T.eq(rec.fee, 1500)
        T.eq(rec.location_id, "central")
        T.eq(rec.status, "impounded")
        T.falsy(H.entities[car], "vehicle removed from the world")
        T.contains(H.lastNotification(owner), "P 555AAA")
        T.eq(H.query("SELECT impounds_issued FROM evora_police_officers WHERE user_id = 100")[1].impounds_issued, 1)
    end)

    T.it("tells the existing garage the vehicle is impounded", function()
        T.truthy(H.ownExports.IsVehicleImpounded("P 555AAA"))
        T.truthy(H.ownExports.IsVehicleImpounded("555AAA"), "registration without prefix")
        local st = H.ownExports.GetImpoundStatus(102, "sultan")
        T.truthy(st and st.impounded)
        T.eq(st.message, L("impound_garage_message"))
        T.eq(#H.ownExports.GetImpoundedVehicles(102), 1)
        T.falsy(H.ownExports.IsVehicleImpounded("P 777BBB"))
    end)

    T.it("blocks a second impound of the same plate", function()
        H.addVehicle("P 555AAA", { x = 3, y = 1, z = 30 }, "sultan")
        impound(officer, "P 555AAA")
        T.eq(H.lastNotification(officer), L("impound_already"))
    end)

    T.it("lists the owner's impounded vehicles in the police inquiry", function()
        H.clearEvents()
        H.prompts(officer, { "102" })
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "استعلامات")
        H.select(officer, "الاستعلام عن المركبات المحجوزة")
        local panel = H.uiEvents(officer, "panel")[1]
        T.eq(panel.kind, "impound")
        T.eq(#panel.data.list, 1)
        T.eq(panel.data.list[1].officer.name, "Rayy")
        T.eq(panel.data.list[1].location, "حجز العاصمة")
    end)

    T.it("lets the owner pay the fee only at an impound centre", function()
        local ok, err = H.rpc(owner, "impound:open", {})
        T.falsy(ok)
        T.eq(err, L("impound_centre_far"))
        local c = Config.Impound.Locations[1].coords
        H.move(owner, c.x, c.y, c.z)
        H.advance(1500)
        local ok2, view = H.rpc(owner, "impound:open", {})
        T.truthy(ok2, tostring(view))
        T.eq(#view.list, 1)
        local ok3, res = H.rpc(owner, "impound:pay", { id = view.list[1].id })
        T.truthy(ok3, tostring(res))
        T.eq(H.user(102).wallet, 8500)
        T.eq(H.query("SELECT status, release_type FROM evora_police_impounds")[1].release_type, "paid")
        T.falsy(H.ownExports.IsVehicleImpounded("P 555AAA"))
    end)

    T.it("lets authorised police release an impounded vehicle after F5", function()
        H.addVehicle("P 555AAA", { x = 3, y = 0, z = 30 }, "sultan")
        H.advance(2000)
        impound(officer, "P 555AAA", "مركبة مهجورة")
        H.confirm(officer, true)
        T.truthy(H.ownExports.IsVehicleImpounded("P 555AAA"))
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "حجز المركبات")
        T.hasNot(H.labels(H.menu(officer)), "فك حجز مركبة", "officers lack impoundRelease")
        H.prompts(commander, { "102" })
        H.choose(commander, H.mainMenu(commander), "الشرطة")
        H.select(commander, "حجز المركبات")
        H.select(commander, "فك حجز مركبة")
        H.selectMatching(commander, "P 555AAA")
        H.confirm(commander, true)
        T.falsy(H.ownExports.IsVehicleImpounded("P 555AAA"))
        local rec = H.query("SELECT * FROM evora_police_impounds ORDER BY id DESC")[1]
        T.eq(rec.release_type, "police")
        T.eq(rec.released_by_name, "Commander")
    end)

    T.it("runs the garage SQL hooks when configured", function()
        H.query("CREATE TABLE IF NOT EXISTS garage_hook (user_id INT, vehicle VARCHAR(50), impounded TINYINT DEFAULT 0)")
        H.query("INSERT INTO garage_hook (user_id, vehicle) VALUES (102, 'sultan')")
        Config.Integrations.VehicleImpound.type = "sql"
        Config.Integrations.VehicleImpound.sql.onImpound = "UPDATE garage_hook SET impounded = 1 WHERE user_id = @owner AND vehicle = @model"
        Config.Integrations.VehicleImpound.sql.onRelease = "UPDATE garage_hook SET impounded = 0 WHERE user_id = @owner AND vehicle = @model"
        H.addVehicle("P 555AAA", { x = 3, y = 0, z = 30 }, "sultan")
        H.advance(2000)
        impound(officer, "P 555AAA", "وقوف مخالف")
        H.confirm(officer, true)
        T.eq(H.query("SELECT impounded FROM garage_hook")[1].impounded, 1)
        Config.Integrations.VehicleImpound.type = "evora"
    end)

    T.it("reminds the owner about impounded vehicles on login", function()
        H.disconnect(owner)
        owner = H.connect(102, { name = "Hossam" })
        T.contains(H.lastNotification(owner), "1")
    end)
end)
