local H, T = ...

local function jailRow(uid) return H.query("SELECT * FROM evora_police_jail WHERE user_id = ?", { uid })[1] end

local function teleports(src)
    local list = {}
    for _, e in ipairs(H.clientEvents(src, "evora_police:teleport")) do list[#list + 1] = e end
    return list
end

T.describe("Jail", function()
    H.boot({ configure = function(cfg) cfg.Webhooks.jail = "https://discord.test/jail" end })
    local officer = H.connect(80, { name = "Rayy", groups = { "ps_officer" }, coords = { x = 0, y = 0, z = 30 } })
    local commander = H.connect(81, { name = "Commander", groups = { "ps_commander" }, coords = { x = 5, y = 5, z = 30 } })
    local target = H.connect(82, { name = "Hossam", coords = { x = 1.5, y = 0, z = 30 } })
    local bystander = H.connect(83, { name = "Walker", coords = { x = 5000, y = 5000, z = 30 } })
    H.rpc(officer, "office:clock", {})
    H.rpc(commander, "office:clock", {})
    local originalTorso = H.user(82).custom[11][1]

    local function sentence(reasonLabel)
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "السجن")
        H.selectMatching(officer, reasonLabel)
        H.select(officer, "Hossam | ID: 82")
    end

    T.it("does not jail without the target's confirmation", function()
        sentence("سرقة")
        local id, card = H.pendingConfirm(target)
        T.truthy(id)
        T.contains(card.message, "Rayy | ID: 80")
        H.confirm(target, false)
        T.falsy(Evora.Jail.isJailed(82))
        T.falsy(jailRow(82))
    end)

    T.it("jails after F5: teleport, cuffs, clothing, HUD, notice and chat", function()
        H.clearEvents()
        sentence("سرقة")
        H.confirm(target, true)
        T.truthy(Evora.Jail.isJailed(82))
        local tp = teleports(target)
        T.truthy(#tp >= 1)
        T.near(tp[#tp].args[1], Config.Jail.Entry.x, 0.01)
        T.truthy(H.user(82).cuffed, "cuffed")
        T.eq(H.user(82).custom[11][1], 146, "jail torso")
        local row = jailRow(82)
        T.eq(row.total_seconds, 1800)
        T.eq(row.was_cuffed, 0)
        T.eq(json.decode(row.clothing)["11"][1], originalTorso, "original clothing saved")
        local hud = H.lastClientEvent(target, "evora_police:jail:start")
        T.eq(hud.args[1].name, Config.Jail.Name)
        T.eq(hud.args[1].remaining, 1800)
        local notice = H.lastNotification(target)
        T.contains(notice, "العسكري: Rayy")
        T.contains(notice, Config.Jail.Name)
        T.contains(notice, "30 دقيقة")
        local chat
        for _, e in ipairs(H.sent) do if e.name == "chat:addMessage" then chat = e.args[1].args[2] end end
        T.eq(chat, "العسكري Rayy | ID: 80 قام بسجن اللاعب Hossam | ID: 82 لمدة 30 دقيقة")
        T.eq(H.query("SELECT jails_issued FROM evora_police_officers WHERE user_id = 80")[1].jails_issued, 1)
    end)

    T.it("counts down on the server only while the prisoner is connected", function()
        H.advance(60 * 1000)
        T.near(Evora.Jail.active[82].remaining, 1740, 1)
        H.disconnect(target)
        T.near(jailRow(82).remaining_seconds, 1740, 1)
        H.advance(120 * 1000)
        T.near(Evora.Jail.active[82].remaining, 1740, 1, "paused while offline")
    end)

    T.it("re-applies the sentence on reconnect without overwriting the saved clothing", function()
        H.clearEvents()
        target = H.connect(82, { name = "Hossam" })
        H.advance(1000)
        T.truthy(#teleports(target) >= 1, "teleported back to jail")
        T.truthy(H.user(82).cuffed)
        T.eq(json.decode(jailRow(82).clothing)["11"][1], originalTorso)
    end)

    T.it("gives a grace period while the client teleports", function()
        H.move(target, Config.Jail.Center.x + 400, Config.Jail.Center.y, 45)
        H.advance(3000)
        T.eq(Evora.Jail.active[82].added, 0, "no escape during the grace period after (re)applying")
        H.move(target, Config.Jail.Entry.x, Config.Jail.Entry.y, 45)
        H.advance(15000)
    end)

    T.it("returns escapees and adds time, never touching non-prisoners", function()
        H.clearEvents()
        local before = Evora.Jail.active[82].remaining
        H.move(target, Config.Jail.Center.x + 400, Config.Jail.Center.y, 45)
        H.advance(3000)
        T.truthy(#teleports(target) >= 1, "returned")
        T.near(Evora.Jail.active[82].remaining, before - 3 + Config.Jail.Escape.AddMinutes * 60, 2)
        T.eq(#teleports(bystander), 0, "a normal player far away is never teleported")
        T.eq(H.lastClientEvent(target, "evora_police:jail:escape").args[1], Config.Jail.Escape.Message)
        H.move(target, Config.Jail.Entry.x, Config.Jail.Entry.y, 45)
    end)

    T.it("caps the time added by escapes", function()
        H.advance(7000) -- past the post-escape grace
        Evora.Jail.active[82].added = Config.Jail.Escape.MaxAddedMinutes * 60 - 30
        local before = Evora.Jail.active[82].remaining
        H.move(target, Config.Jail.Center.x + 400, Config.Jail.Center.y, 45)
        H.advance(3000)
        H.move(target, Config.Jail.Entry.x, Config.Jail.Entry.y, 45)
        T.near(Evora.Jail.active[82].remaining, before - 3 + 30, 2)
        T.eq(Evora.Jail.active[82].added, Config.Jail.Escape.MaxAddedMinutes * 60)
    end)

    T.it("survives a resource restart", function()
        H.advance(Config.Jail.PersistInterval * 1000)
        local remaining = Evora.Jail.active[82].remaining
        TriggerEvent("onResourceStop", "Evora_Police")
        H.settle()
        H.restart()
        T.truthy(Evora.Jail.isJailed(82))
        T.near(Evora.Jail.active[82].remaining, remaining, 2)
        T.eq(json.decode(jailRow(82).clothing)["11"][1], originalTorso)
    end)

    T.it("validates jail tasks on the server (position, duration, cooldown)", function()
        local task = Config.Jail.Tasks.List[1]
        local ok, err = H.rpc(target, "jail:taskStart", { id = task.id })
        T.falsy(ok)
        T.eq(err, L("jail_task_far"))
        H.move(target, task.coords.x, task.coords.y, task.coords.z)
        H.advance(1500)
        local ok2, info = H.rpc(target, "jail:taskStart", { id = task.id })
        T.truthy(ok2, tostring(info))
        T.eq(info.duration, task.duration)
        H.advance(1500)
        local ok3, err3 = H.rpc(target, "jail:taskComplete", { id = task.id, success = true })
        T.falsy(ok3)
        T.eq(err3, L("jail_task_too_fast"))
        H.advance(1500)
        T.truthy((H.rpc(target, "jail:taskStart", { id = task.id })))
        H.advance(task.duration * 1000)
        local before = Evora.Jail.active[82].remaining
        local ok4, res = H.rpc(target, "jail:taskComplete", { id = task.id, success = true })
        T.truthy(ok4, tostring(res))
        T.eq(res.reduced, task.reduction)
        T.near(Evora.Jail.active[82].remaining, before - task.reduction, 1)
        H.advance(1500)
        local ok5, err5 = H.rpc(target, "jail:taskComplete", { id = task.id, success = true })
        T.falsy(ok5, "duplicate reward")
        H.advance(1500)
        local ok6, err6 = H.rpc(target, "jail:taskStart", { id = task.id })
        T.falsy(ok6)
        T.contains(err6, "ثانية")
        T.truthy((H.rpc(target, "jail:taskCancel", {})))
    end)

    T.it("lets authorised staff modify the remaining time after their own F5", function()
        local before = Evora.Jail.active[82].remaining
        H.prompts(commander, { "10" })
        H.choose(commander, H.mainMenu(commander), "الشرطة")
        H.select(commander, "استعلامات")
        H.select(commander, "تعديل مدة السجن")
        H.select(commander, "Hossam | ID: 82")
        H.select(commander, "إضافة مدة")
        H.confirm(commander, true)
        T.near(Evora.Jail.active[82].remaining, before + 600, 2)
        local denied = H.labels(H.mainMenu(officer))
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "استعلامات")
        T.hasNot(H.labels(H.menu(officer)), "تعديل مدة السجن", "officers lack jailModify")
    end)

    T.it("checks a prisoner status from استعلامات", function()
        H.clearEvents()
        H.prompts(officer, { "82" })
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "استعلامات")
        H.select(officer, "التحقق من سجن لاعب")
        local panel = H.uiEvents(officer, "panel")[1]
        T.eq(panel.kind, "jail")
        T.truthy(panel.data.jailed)
        T.eq(panel.data.officer.name, "Rayy")
        T.eq(panel.data.jailName, Config.Jail.Name)
    end)

    T.it("monitors a prisoner with the shared spectate service", function()
        H.choose(commander, H.mainMenu(commander), "الشرطة")
        H.select(commander, "استعلامات")
        H.select(commander, "مراقبة سجين")
        H.select(commander, "Hossam | ID: 82")
        T.truthy(Evora.Spectate.isSpectating(commander))
        T.eq(H.lastClientEvent(commander, "evora_police:spectate:start").args[1].kind, "prisoner")
        H.rpc(commander, "spectate:stop", {})
    end)

    T.it("releases with a mandatory reason, restoring clothing, cuffs and position", function()
        H.clearEvents()
        local before = #H.http
        H.prompts(commander, { "حسن سيرة وسلوك" })
        H.choose(commander, H.mainMenu(commander), "الشرطة")
        H.select(commander, "استعلامات")
        H.select(commander, "فك سجن")
        H.select(commander, "Hossam | ID: 82")
        H.confirm(commander, true)
        T.falsy(Evora.Jail.isJailed(82))
        T.falsy(jailRow(82))
        T.eq(H.user(82).custom[11][1], originalTorso, "clothing restored")
        T.falsy(H.user(82).cuffed, "uncuffed")
        local tp = teleports(target)
        T.near(tp[#tp].args[1], Config.Jail.Exit.x, 0.01)
        local hist = H.query("SELECT * FROM evora_police_jail_history WHERE user_id = 82 ORDER BY id DESC")[1]
        T.eq(hist.end_type, "released")
        T.eq(hist.release_reason, "حسن سيرة وسلوك")
        H.advance(3000)
        local found = false
        for i = before + 1, #H.http do
            if H.http[i].url == "https://discord.test/jail" and H.http[i].body:find("حسن سيرة وسلوك", 1, true) then found = true end
        end
        T.truthy(found, "release reason sent to the jail webhook")
    end)

    T.it("releases automatically when the sentence is served", function()
        H.move(target, 1.5, 0, 30)
        H.advance(6000)
        H.clearEvents()
        sentence("مقاومة رجال الأمن")
        H.confirm(target, true)
        T.truthy(Evora.Jail.isJailed(82))
        H.advance(15 * 60 * 1000 + 2000)
        T.falsy(Evora.Jail.isJailed(82))
        T.truthy(H.lastClientEvent(target, "evora_police:jail:end"))
        local hist = H.query("SELECT end_type FROM evora_police_jail_history WHERE user_id = 82 ORDER BY id DESC")[1]
        T.eq(hist.end_type, "served")
    end)
end)
