local H, T = ...

T.describe("Reports, wanted persons and citizen inquiry", function()
    H.boot()
    local officer = H.connect(60, { name = "Rayy", groups = { "ps_officer" } })
    local officer2 = H.connect(61, { name = "Nawaf", groups = { "ps_officer" } })
    local deputy = H.connect(62, { name = "Deputy", groups = { "ps_deputy" } })
    local citizen = H.connect(63, { name = "Fahad", coords = { x = 250.0, y = -800.0, z = 30.0 } })
    local suspect = H.connect(64, { name = "Hossam" })
    H.rpc(officer, "office:clock", {})
    H.rpc(officer2, "office:clock", {})
    H.rpc(deputy, "office:clock", {})

    T.it("offers إبلاغ عن مجرم to everyone and الشرطة only to officers", function()
        local labels = H.labels(H.mainMenu(citizen))
        T.has(labels, "إبلاغ عن مجرم")
        T.hasNot(labels, "الشرطة")
        T.has(H.labels(H.mainMenu(officer)), "الشرطة")
    end)

    T.it("creates a report from the citizen popup and alerts on-duty officers", function()
        H.vrp.calls = {}
        H.prompts(citizen, { "64", "سرق سيارتي من أمام المنزل" })
        H.choose(citizen, H.mainMenu(citizen), "إبلاغ عن مجرم")
        local r = H.query("SELECT * FROM evora_police_reports")[1]
        T.truthy(r, "report row")
        T.eq(r.reporter_id, 63)
        T.eq(r.reporter_name, "Fahad")
        T.eq(r.target_id, 64)
        T.eq(r.target_name, "Hossam")
        T.eq(r.status, "new")
        T.near(r.pos_x, 250, 0.1)
        T.contains(H.lastNotification(officer), "Hossam | ID: 64")
        T.contains(H.lastNotification(citizen), "#" .. r.id)
    end)

    T.it("rejects unknown ids and spam", function()
        H.prompts(citizen, { "9999", "test" })
        H.choose(citizen, H.mainMenu(citizen), "إبلاغ عن مجرم")
        T.eq(H.lastNotification(citizen), L("report_cooldown", { seconds = 60 }))
        H.advance(61000)
        H.prompts(citizen, { "9999", "test" })
        H.choose(citizen, H.mainMenu(citizen), "إبلاغ عن مجرم")
        T.eq(H.lastNotification(citizen), L("err_unknown_id"))
        T.eq(#H.query("SELECT id FROM evora_police_reports"), 1)
    end)

    T.it("lets exactly one officer claim a report and informs the reporter", function()
        local ok, res = H.rpc(officer, "reports:list", {})
        T.truthy(ok, tostring(res))
        T.eq(#res.list, 1)
        local id = res.list[1].id
        T.eq(res.list[1].reporter.name, "Fahad")
        local ok1, claimed = H.rpc(officer, "reports:claim", { id = id })
        T.truthy(ok1, tostring(claimed))
        T.eq(claimed.status, "claimed")
        T.eq(claimed.assigned.name, "Rayy")
        local ok2, err2 = H.rpc(officer2, "reports:claim", { id = id })
        T.falsy(ok2)
        T.eq(err2, L("report_already_claimed"))
        T.contains(H.lastNotification(citizen), "Rayy")
    end)

    T.it("follows the status workflow and credits the assigned officer", function()
        local id = H.query("SELECT id FROM evora_police_reports")[1].id
        local ok, err = H.rpc(officer2, "reports:setStatus", { id = id, status = "processing" })
        T.falsy(ok)
        T.eq(err, L("report_not_assigned"))
        T.truthy((H.rpc(officer, "reports:setStatus", { id = id, status = "processing" })))
        H.advance(1000)
        T.truthy((H.rpc(officer, "reports:setStatus", { id = id, status = "closed" })))
        H.advance(1000)
        local ok3 = H.rpc(officer, "reports:setStatus", { id = id, status = "processing" })
        T.falsy(ok3, "closed is final")
        T.eq(H.query("SELECT reports_handled FROM evora_police_officers WHERE user_id = 60")[1].reports_handled, 1)
    end)

    T.it("sets a waypoint to where the report was filed", function()
        local id = H.query("SELECT id FROM evora_police_reports")[1].id
        T.truthy((H.rpc(officer, "reports:waypoint", { id = id })))
        local ev = H.lastClientEvent(officer, "evora_police:waypoint")
        T.near(ev.args[1], 250, 0.1)
    end)

    T.it("creates a wanted notice from the police menu and alerts on-duty officers", function()
        H.prompts(officer, { "64", "مطلوب في قضية سرقة" })
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "تعميم بلاغ")
        local w = H.query("SELECT * FROM evora_police_wanted")[1]
        T.truthy(w)
        T.eq(w.target_name, "Hossam")
        T.eq(w.created_by_name, "Rayy")
        T.eq(w.active, 1)
        T.truthy(H.lastClientEvent(officer2, "evora_police:wanted:alert"))
        H.prompts(officer, { "64", "مرة أخرى" })
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "تعميم بلاغ")
        T.eq(H.lastNotification(officer), L("wanted_exists"))
    end)

    T.it("lists wanted persons with job and FiveM names, and restricts removal", function()
        local ok, list = H.rpc(officer, "wanted:list", {})
        T.truthy(ok, tostring(list))
        T.eq(#list, 1)
        T.eq(list[1].target.name, "Hossam")
        T.eq(list[1].target.id, 64)
        T.eq(list[1].job, Config.Integrations.Job.unemployed)
        T.eq(list[1].createdBy.name, "Rayy")
        local ok2, err2 = H.rpc(officer, "wanted:clear", { id = list[1].id })
        T.falsy(ok2)
        T.eq(err2, L("err_no_permission"))
        T.truthy((H.rpc(deputy, "wanted:clear", { id = list[1].id })))
        local _, after = H.rpc(officer, "wanted:list", {})
        T.eq(#after, 0)
    end)

    T.it("shows the citizen card with job, fines and wanted status", function()
        H.vrp.users[64].groups.taxi = true
        H.query("INSERT INTO evora_police_fines (target_id, target_name, officer_id, officer_name, category, category_label, fine_id, label, amount, status, created_at) VALUES (64, 'Hossam', 60, 'Rayy', 'traffic', 'مرورية', 'speeding', 'تجاوز السرعة', 1500, 'unpaid', 1)")
        H.prompts(officer, { "64", "تعميم جديد" })
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "تعميم بلاغ")
        H.clearEvents()
        H.prompts(officer, { "64" })
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "استعلام عن مواطن")
        local panel = H.uiEvents(officer, "panel")[1]
        T.truthy(panel, "panel sent")
        T.eq(panel.kind, "citizen")
        T.eq(panel.data.name, "Hossam")
        T.eq(panel.data.user_id, 64)
        T.eq(panel.data.job, "سائق تاكسي")
        T.eq(panel.data.fines.count, 1)
        T.eq(panel.data.fines.total, 1500)
        T.truthy(panel.data.wanted.active)
    end)
end)
