local H, T = ...

T.describe("Security alert", function()
    H.boot()
    local zone = Config.SecurityAlert.Zones[1]
    local deputy = H.connect(110, { name = "Deputy", groups = { "ps_deputy" }, coords = { x = 0, y = 0, z = 30 } })
    local inside = H.connect(111, { name = "Inside", coords = { x = zone.coords.x + 10, y = zone.coords.y, z = 30 } })
    local outside = H.connect(112, { name = "Outside", coords = { x = zone.coords.x + zone.radius + 50, y = zone.coords.y, z = 30 } })
    local officer = H.connect(113, { name = "Officer", groups = { "ps_officer" } })
    H.rpc(deputy, "office:clock", {})

    T.it("is not offered to ranks without the securityAlert permission", function()
        H.rpc(officer, "office:clock", {})
        H.choose(officer, H.mainMenu(officer), "الشرطة")
        H.select(officer, "الأدوات الأمنية")
        T.hasNot(H.labels(H.menu(officer)), "الاستنفار الأمني")
    end)

    T.it("exempts only players already inside when the alert starts", function()
        H.clearEvents()
        H.choose(deputy, H.mainMenu(deputy), "الشرطة")
        H.select(deputy, "الأدوات الأمنية")
        H.select(deputy, "الاستنفار الأمني")
        H.select(deputy, "بدء استنفار")
        H.select(deputy, zone.label)
        local evIn = H.lastClientEvent(inside, "evora_police:alert:start")
        local evOut = H.lastClientEvent(outside, "evora_police:alert:start")
        T.truthy(evIn and evOut)
        T.eq(evIn.args[2], true, "inside at activation → exempt")
        T.eq(evOut.args[2], false, "outside → affected when entering")
        T.eq(evIn.args[1].radius, zone.radius)
        T.eq(evIn.args[1].vehicle.maxSpeed, Config.SecurityAlert.VehicleSlowdown.maxSpeed)
        T.eq(#H.uiEvents(outside, "broadcast"), 1, "citizens are informed")
    end)

    T.it("affects players who join after the start", function()
        local late = H.connect(114, { name = "Late", coords = { x = zone.coords.x, y = zone.coords.y, z = 30 } })
        local ev = H.lastClientEvent(late, "evora_police:alert:sync")
        T.truthy(ev, "late joiner receives the active alert without exemption")
        T.eq(#ev.args[1], 1)
    end)

    T.it("clears every effect when the alert stops", function()
        H.choose(deputy, H.mainMenu(deputy), "الشرطة")
        H.select(deputy, "الأدوات الأمنية")
        H.select(deputy, "الاستنفار الأمني")
        H.select(deputy, "إيقاف استنفار")
        H.select(deputy, zone.label)
        local stop = H.lastClientEvent(inside, "evora_police:alert:stop")
        T.truthy(stop)
        T.eq(Utils.count(Evora.Alert.active), 0)
    end)
end)
